### ISSUE TITLE
ERROR: Double requirement given

### ISSUE THREAD

**Issue by jonaslejon** [fr0gger/unprotect#1]
Installing a new fresh version in virtualenv gives the following error:

`ERROR: Double requirement given: urllib3>=1.24.2 (from -r requirements.txt (line 18)) (already in urllib3>=1.23 (from -r requirements.txt (line 15)), name='urllib3')`

OS:
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Kali
Description:	Kali GNU/Linux Rolling
Release:	2019.2
Codename:	n/a

Python version:
Python 2.7.16

Virtualenv version:
15.1.0

**Comment by fr0gger** [comment]
Corrected! it should be okay now!
